FROM alpine
WORKDIR /root/dockerprac
COPY HelloWorld.java /root/dockerprac
RUN apk add openjdk8
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
ENV PATH $PATH:$JAVA_HOME/bin
RUN javac HelloWorld.java
ENTRYPOINT java HelloWorld
